#!/usr/bin/env node

var program = require('commander');

program
   .version('0.0.1')
   .command('install [folder]', 'Install Bamburgs').alias('i')
   .command('update', 'Updates Bamburgs').alias('u')
   .parse(process.argv);
