#!/usr/bin/env node

const program  = require('commander');
const shell    = require('shelljs');
const crypto   = require('crypto');
const readline = require('readline');
const download = require('download-git-repo');
const fs       = require('fs-extra');

program
  .option('-b, --build', 'Run npm install and build')
  .parse(process.argv);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});
console.log('\n**********************************************');
console.log('Welcome to Bamburgs...let\'s get you all set up ok!' );
console.log('We need to build up your package.json file so we\'re');
console.log('to ask you some questions.')
console.log('**********************************************\n');

rl.question('What\'s your project name? ', (name) => {
   if (!name) {
      console.log('Sorry we need a name');
      process.exit(0);
   }
   rl.question('\nWhere do you want the compiled files to go? (dist/assets)', (dist) => {
      dist = !dist ? 'dist/assets' : dist;
      rl.question('\nWhere do you want your source files to live? (src) ', (src) => {
         src = !src ? 'src' : src;
         rl.question('\nDescription: ', (description) => {
            description = !description ? 'I like turdles' : description;
            rl.question('\nYour Name: ', (author) => {
               author = !author ? 'Namey McNameFace' : author;
               rl.question('\nYour Email: ', (email) => {
                  email = !email ? '' : email;
                  setupFiles(name, dist, src, description, author, email);

                  rl.close();
               });
            });
         });
      });
   });
});

function setupFiles(name, dist, src, description, author, email) {
   let hash = crypto.createHash('md5').update(name).digest('hex');
   let location = `${process.cwd()}/${hash}`;

   download('mettleshop/bamburgs', location, (err) => {
      let package = location + '/package.template';
      let gitignore = location + '/gitignore.template';

      if (err) {
         console.log(err);
         process.exit(0);
      }

      fs.readFile(package,'utf8', (err, data) => {
         let result = data
                        .replace('{{name}}', name)
                        .replace('{{author}}', author)
                        .replace('{{description}}', description)
                        .replace('{{dist}}', dist)
                        .replace('{{src}}', src)
                        .replace('{{email}}', email);

         fs.writeFile(process.cwd() + '/package.json', result, 'utf8', function (err) {
            if (err) return console.log(err);
         });
      });

      fs.readFile(gitignore, 'utf8', (err, data) => {
         let result = data.replace('{{dist}}', dist);

         fs.writeFile(process.cwd() + '/.gitignore', result, 'utf8', function (err) {
            if (err) return console.log(err);
         });
      });

      fs.copy(location+"/postcss.config.js", process.cwd()+"/postcss.config.js", (err) => {
         fs.copy(location+"/.sass-lint.yml", process.cwd()+"/.sass-lint.yml", (err) => {
            fs.copy(location+"/.editorconfig", process.cwd()+"/.editorconfig", (err) => {
               fs.copy(location+"/.babelrc", process.cwd()+"/.babelrc", (err) => {
                  fs.copy(location+"/src", process.cwd()+"/"+src, (err) => {
                     fs.remove(location);

                     if (program.build) {
                        console.log('running NPM Install...');
                        shell.exec('npm install');
                        console.log();
                        console.log('Building...');
                        shell.exec('npm run build');
                     }

                     console.log('Ready to Go!')
                  });
               });
            });
         });
      });
   });
}
